name: PyInstaller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyside6

      - name: Build executable
        run: |
          pyinstaller --onefile main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prettyproject-${{ matrix.os }}
          path: dist/main${{ runner.os == 'Windows' && '.exe' || '' }}
  build-for-intel-mac:
    runs-on: mac-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - uses: actions/checkout@v3
      - name: Setup Python
        run: |
          brew update
          brew install python@3.12
          echo 'export PATH="/usr/local/opt/python@3.12/bin:$PATH"' >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pip
      - name: Build executable
        run: |
          pyinstaller --onefile main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prettyproject-mac-intel
          path: dist/main
      
